spring:
  application:
    name: Book Keeper

  main:
    banner-mode: off
    web-application-type: none

  datasource:
    url: jdbc:postgresql://localhost:5432/bookkeeper_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

  sql:
    init:
      mode: never

  ai:
    mcp:
      server:
        stdio: true
        type: SYNC
        annotation-scanner:
          enabled: true

logging:
  pattern:
    console: ""

server:
  port: 8080